import { BarChart3, ClipboardCheck, FileWarning, Flag, Link as LinkIcon } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Empty, ErrorNotice, Loading, PageHeader, Status, useResource } from '../../components/ui';
import { api } from '../../services/api';

type DashboardData={counts:Record<string,number>;highValue:number;possibleDuplicates:number;missingDocuments:number;amountMismatches:number;averageAuditDays:number|null;departmentBreakdown:{name:string;count:number}[];recent:{id:string;action:string;actorName:string;createdAt:string;entityId:string|null}[];queue:{id:string;reference:string;lecturer:string;department:string;eligibleHours:string;submittedAt:string|null}[]};
const metric=(data:DashboardData,status:string)=>data.counts[status]??0;
export function AuditDashboard(){
  const result=useResource<{data:DashboardData}>(()=>api('/reports/audit-dashboard'));
  if(result.loading)return <Loading/>;
  if(result.error)return <ErrorNotice message={result.error}/>;
  const data=result.data!.data;const highest=Math.max(1,...data.departmentBreakdown.map(item=>item.count));
  return <><PageHeader eyebrow="INTERNAL AUDIT" title="Audit control centre" description="Verify authorized claims, surface exceptions, and clear only complete records for Finance."/>
    <section className="metric-grid audit-metrics"><article><span>Awaiting audit</span><strong>{metric(data,'AUDIT_REVIEW')}</strong></article><article><span>Cleared</span><strong>{metric(data,'AUDIT_CLEARED')}</strong></article><article><span>Queries open</span><strong>{metric(data,'AUDIT_QUERY')}</strong></article><article><span>Rejected</span><strong>{metric(data,'AUDIT_REJECTED')}</strong></article></section>
    <section className="dashboard-columns"><div className="workspace-section"><div className="section-heading"><div><h2>Audit queue</h2><p>Claims waiting for independent verification.</p></div><Link to="/claims?status=AUDIT_REVIEW" className="text-button">Open audit queue</Link></div>{data.queue.length?<div className="table-scroll"><table><thead><tr><th>Claim</th><th>Lecturer</th><th>Department</th><th>Eligible hours</th><th></th></tr></thead><tbody>{data.queue.map(claim=><tr key={claim.id}><td>{claim.reference}</td><td>{claim.lecturer}</td><td>{claim.department}</td><td>{claim.eligibleHours}</td><td><Link className="icon-button" title="Review claim" aria-label={`Review ${claim.reference}`} to={`/claims/${claim.id}`}><LinkIcon size={16}/></Link></td></tr>)}</tbody></table></div>:<Empty title="Audit queue is clear" message="There are no claims awaiting audit review."/>}</div>
      <div className="workspace-section"><div className="section-heading"><div><h2>Risk indicators</h2><p>Signals to guide review, not automatic decisions.</p></div><Flag size={18}/></div><dl className="signal-list"><div><dt><BarChart3 size={16}/>High-value claims</dt><dd>{data.highValue}</dd></div><div><dt><FileWarning size={16}/>Possible duplicates</dt><dd>{data.possibleDuplicates}<small>Detection pending</small></dd></div><div><dt><ClipboardCheck size={16}/>Average audit time</dt><dd>{data.averageAuditDays===null?'No completed audits':`${data.averageAuditDays} days`}</dd></div></dl></div></section>
    <section className="dashboard-columns"><div className="workspace-section"><div className="section-heading"><div><h2>Claims by department</h2><p>Audit-visible claim volume.</p></div></div><div className="bar-list">{data.departmentBreakdown.length?data.departmentBreakdown.map(item=><div key={item.name}><span>{item.name}</span><div><i style={{width:`${item.count/highest*100}%`}}/></div><strong>{item.count}</strong></div>):<p className="muted-copy">Department data will appear as claims enter audit.</p>}</div></div>
      <div className="workspace-section"><div className="section-heading"><div><h2>Recent audit activity</h2><p>Decisions recorded in the immutable system log.</p></div></div><ul className="activity-list">{data.recent.length?data.recent.map(item=><li key={item.id}><span className="activity-dot"/><div><strong>{item.action.replaceAll('_',' ')}</strong><p>{item.actorName} · {new Intl.DateTimeFormat('en-GH',{dateStyle:'medium'}).format(new Date(item.createdAt))}</p></div>{item.entityId&&<Link to={`/claims/${item.entityId}`} className="text-button">View</Link>}</li>):<li className="muted-copy">No completed audit decisions yet.</li>}</ul></div></section>
  </>;
}
