import 'dotenv/config';
import { expect, test } from '@playwright/test';

test('administrator workspace, profile, academic records and mobile navigation',async({page})=>{
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('/');
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('Staff ID or email address').fill('admin@example.test');
  await page.getByLabel('Password',{exact:true}).fill(process.env.SEED_PASSWORD!);
  await page.getByRole('button',{name:'Sign in to your workspace'}).click();
  await expect(page).toHaveURL(/\/admin\/dashboard$/);
  await expect(page.getByRole('heading',{name:'Welcome, Portal Administrator'})).toBeVisible();
  await expect(page.getByText('Staff accounts',{exact:true}).first()).toBeVisible();
  await page.screenshot({path:'test-results/admin-desktop.png',fullPage:true});
  await page.getByRole('navigation',{name:'Workspace'}).getByRole('link',{name:'Staff accounts'}).click();
  await expect(page.getByText('Dr. Ama Mensah',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Add staff'}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(page.getByRole('button',{name:'Add staff'})).toBeFocused();
  await page.getByRole('link',{name:'Academic records',exact:true}).click();
  await page.getByRole('tab',{name:'Semesters',exact:true}).click();
  await expect(page.getByRole('cell',{name:'First Semester',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Add record'}).click();
  await expect(page.getByLabel('Academic year')).toContainText('2026/2027');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('link',{name:'My profile'}).click();
  await page.getByRole('button',{name:'Save profile'}).click();
  await expect(page.getByRole('status')).toContainText('Profile saved.');
  await page.reload();
  await expect(page.getByRole('heading',{name:'My profile',exact:true})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Open navigation'}).click();
  await page.getByRole('navigation',{name:'Workspace'}).getByRole('link',{name:'Overview'}).click();
  await expect(page.getByRole('heading',{name:'Welcome, Portal Administrator'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/admin-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Open navigation'}).click();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await expect(page).toHaveURL(/\/login$/);
});

test('lecturer cannot navigate into administration',async({page})=>{
  await page.goto('/login');
  await page.getByLabel('Staff ID or email address').fill('lecturer@example.test');
  await page.getByLabel('Password',{exact:true}).fill(process.env.SEED_PASSWORD!);
  await page.getByRole('button',{name:'Sign in to your workspace'}).click();
  await expect(page).toHaveURL(/\/lecturer\/dashboard$/);
  await expect(page.getByRole('heading',{name:'Recent claims',exact:true})).toBeVisible();
  await page.goto('/admin/users');
  await expect(page.getByRole('heading',{name:'Access denied'})).toBeVisible();
  await page.goto('/missing-page');
  await expect(page.getByRole('heading',{name:'Page not found'})).toBeVisible();
});

test('lecturer draft persists, validates submission, and can be cancelled',async({page})=>{
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('/login');
  await page.getByLabel('Staff ID or email address').fill('lecturer@example.test');
  await page.getByLabel('Password',{exact:true}).fill(process.env.SEED_PASSWORD!);
  await page.getByRole('button',{name:'Sign in to your workspace'}).click();
  await expect(page).toHaveURL(/\/lecturer\/dashboard$/);
  await page.getByRole('navigation',{name:'Workspace'}).getByRole('link',{name:'Claims',exact:true}).click();
  await page.getByRole('link',{name:'New claim'}).click();
  await page.getByLabel('Academic year and semester').selectOption({label:'2026/2027 / First Semester'});
  await page.getByRole('button',{name:'Add course',exact:true}).click();
  const courseItem=page.getByRole('group',{name:'Course 1'});
  await courseItem.getByRole('combobox',{name:'Course'}).selectOption({label:'DEMO-ACC201 - Financial Accounting'});
  await courseItem.getByRole('textbox',{name:'Start date'}).fill('2026-09-07');
  await courseItem.getByRole('textbox',{name:'End date'}).fill('2026-10-04');
  await courseItem.getByRole('spinbutton',{name:'Weekly hours'}).fill('2.5');
  await courseItem.getByRole('spinbutton',{name:'Weeks'}).fill('4');
  await page.getByLabel('Claim remarks').fill('Browser regression fixture - retained as a cancelled development claim.');
  await expect(page.locator('.claim-savebar strong')).toHaveText('10');
  await page.screenshot({path:'test-results/claim-editor-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await expect(page).toHaveURL(/\/claims\/[0-9a-f-]+$/);
  await page.reload();
  await expect(page.getByText('Browser regression fixture - retained as a cancelled development claim.',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Edit draft',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('group',{name:'Course 1'}).getByRole('spinbutton',{name:'Weekly hours'}).fill('3');
  await expect(page.locator('.claim-savebar strong')).toHaveText('12');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/claim-editor-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await page.getByRole('button',{name:'Submit to HOD',exact:true}).click();
  await page.getByRole('button',{name:'Confirm submission',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText(/policy|assignments/i);
  await page.getByRole('button',{name:'Go back',exact:true}).click();
  await page.getByRole('button',{name:'Cancel draft',exact:true}).click();
  await page.getByRole('button',{name:'Confirm cancellation',exact:true}).click();
  await expect(page.locator('.page-heading').getByText('Cancelled',{exact:true})).toBeVisible();
  await expect(page.getByText('Cancelled by lecturer',{exact:true})).toBeVisible();
});
