import { Banknote, Clock3, Link as LinkIcon, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Empty, ErrorNotice, Loading, PageHeader, Status, money, useResource } from '../../components/ui';
import { api } from '../../services/api';

type FinanceData={counts:Record<string,number>;totals:{outstanding:string;paidToday:string;paidThisMonth:string;paidThisYear:string};queue:{id:string;reference:string;lecturer:string;department:string;createdAt:string}[];recent:{id:string;reference:string;status:string;lecturer:string;department:string;payment:{amount:string;currency:string;status:string;paidOn:string|null;reference:string|null}|null}[]};
export function FinanceDashboard(){
  const result=useResource<{data:FinanceData}>(()=>api('/reports/finance-dashboard'));
  if(result.loading)return <Loading/>;
  if(result.error)return <ErrorNotice message={result.error}/>;
  const data=result.data!.data;
  return <><PageHeader eyebrow="FINANCE" title="Payment operations" description="Process only claims that Internal Audit has cleared. Approved claim data remains read-only."/>
    <section className="metric-grid finance-metrics"><article><span>Awaiting payment</span><strong>{data.counts.AUDIT_CLEARED??0}</strong></article><article><span>In processing</span><strong>{(data.counts.FINANCE_PROCESSING??0)+(data.counts.PAYMENT_PENDING??0)}</strong></article><article><span>Outstanding value</span><strong>{money(data.totals.outstanding)}</strong></article><article><span>Paid this month</span><strong>{money(data.totals.paidThisMonth)}</strong></article></section>
    <section className="dashboard-columns"><div className="workspace-section"><div className="section-heading"><div><h2>Ready for payment</h2><p>Claims cleared by Internal Audit and ready for Finance.</p></div><Link to="/claims?status=AUDIT_CLEARED" className="text-button">Open payment queue</Link></div>{data.queue.length?<div className="table-scroll"><table><thead><tr><th>Claim</th><th>Payee</th><th>Department</th><th>Audit status</th><th></th></tr></thead><tbody>{data.queue.map(claim=><tr key={claim.id}><td>{claim.reference}</td><td>{claim.lecturer}</td><td>{claim.department}</td><td><Status status="AUDIT_CLEARED"/></td><td><Link className="icon-button" title="Process claim" aria-label={`Process ${claim.reference}`} to={`/claims/${claim.id}`}><LinkIcon size={16}/></Link></td></tr>)}</tbody></table></div>:<Empty title="No claims ready for payment" message="Audit-cleared claims will appear here."/>}</div>
      <div className="workspace-section"><div className="section-heading"><div><h2>Payment totals</h2><p>Current payment ledger summary.</p></div><WalletCards size={18}/></div><dl className="signal-list"><div><dt><Clock3 size={16}/>Paid today</dt><dd>{money(data.totals.paidToday)}</dd></div><div><dt><Banknote size={16}/>Paid this year</dt><dd>{money(data.totals.paidThisYear)}</dd></div><div><dt><WalletCards size={16}/>Failed payments</dt><dd>{data.counts.PAYMENT_FAILED??0}</dd></div></dl></div></section>
    <section className="workspace-section"><div className="section-heading"><div><h2>Recent payment records</h2><p>Payment records are linked to their source claims.</p></div></div>{data.recent.length?<div className="table-scroll"><table><thead><tr><th>Claim</th><th>Lecturer</th><th>Payment</th><th>Status</th><th>Reference</th></tr></thead><tbody>{data.recent.map(item=><tr key={item.id}><td><Link to={`/claims/${item.id}`}>{item.reference}</Link></td><td>{item.lecturer}<small>{item.department}</small></td><td>{item.payment?money(item.payment.amount,item.payment.currency):'Not calculated'}</td><td><Status status={item.status}/></td><td>{item.payment?.reference??'Not recorded'}</td></tr>)}</tbody></table></div>:<Empty title="No payment records yet" message="Payment activity will appear here after Finance begins processing."/>}</section>
  </>;
}
