import { FormEvent, useState } from 'react';
import { Printer, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../app/auth';
import { api } from '../../services/api';
import { Empty, ErrorNotice, Loading, PageHeader, Status, useResource } from '../../components/ui';

type AuditReport={metrics:{awaiting:number;cleared:number;queried:number;rejected:number;flags:number;averageDays:number|null};departments:{name:string;count:number}[];decisions:{id:string;action:string;actorName:string;entityId:string|null;createdAt:string}[];claims:{id:string;reference:string;status:string;lecturer:{name:string;staffId:string};department:{name:string};decision:{comment:string}|null}[]};
type FinanceReport={metrics:{awaiting:number;processing:number;paid:number;failed:number};totals:{currency:string;paid:string;outstanding:string}[];payments:{id:string;reference:string;status:string;lecturer:{name:string;staffId:string};department:{name:string};payment:{amount:string;currency:string;reference:string|null}|null}[]};
const Metric=({label,value}:{label:string;value:number})=><article><span>{label}</span><strong>{value}</strong></article>;
function Filters({filters,setFilters,submit}:{filters:{from:string;to:string};setFilters:(v:{from:string;to:string})=>void;submit:(e:FormEvent)=>void}){return <form className="list-toolbar report-filters" onSubmit={submit}><label>From<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><button className="button secondary"><Search size={17}/>Apply</button><button className="button ghost" type="button" onClick={()=>window.print()}><Printer size={17}/>Print</button></form>;}
function AuditReports(){const [filters,setFilters]=useState({from:'',to:''});const [query,setQuery]=useState(filters);const params=new URLSearchParams(Object.entries(query).filter(([,v])=>v));const result=useResource<{data:AuditReport}>(()=>api(`/reports/audit?${params}`),[params.toString()]);const data=result.data?.data;return <><PageHeader eyebrow="INTERNAL AUDIT" title="Audit reports" description="Independent assurance outcomes, exceptions, turnaround, and audit decisions."/><Filters filters={filters} setFilters={setFilters} submit={e=>{e.preventDefault();setQuery(filters);}}/><ErrorNotice message={result.error}/>{result.loading?<Loading/>:data?<><section className="metric-grid"><Metric label="Awaiting audit" value={data.metrics.awaiting}/><Metric label="Cleared for payment" value={data.metrics.cleared}/><Metric label="Open queries" value={data.metrics.queried}/><Metric label="Rejected" value={data.metrics.rejected}/></section><section className="dashboard-columns"><div className="workspace-section"><h2>Audit outcomes</h2><div className="table-scroll"><table><tbody><tr><th>Audit flags raised</th><td>{data.metrics.flags}</td></tr><tr><th>Average audit turnaround</th><td>{data.metrics.averageDays===null?'No completed audits':`${data.metrics.averageDays} days`}</td></tr>{data.departments.map(row=><tr key={row.name}><th>{row.name}</th><td>{row.count} claims</td></tr>)}</tbody></table></div></div><div className="workspace-section"><h2>Recent audit decisions</h2><ul className="activity-list">{data.decisions.length?data.decisions.map(item=><li key={item.id}><span className="activity-dot"/><div><strong>{item.action.replaceAll('_',' ')}</strong><p>{item.actorName} · {new Intl.DateTimeFormat('en-GH',{dateStyle:'medium'}).format(new Date(item.createdAt))}</p></div>{item.entityId&&<Link className="text-button" to={`/claims/${item.entityId}`}>View</Link>}</li>):<li className="muted-copy">No audit decisions in this period.</li>}</ul></div></section><section className="workspace-section"><h2>Audit register</h2>{data.claims.length?<div className="table-scroll"><table><thead><tr><th>Claim</th><th>Lecturer</th><th>Department</th><th>Audit outcome</th><th>Decision note</th></tr></thead><tbody>{data.claims.map(claim=><tr key={claim.id}><td><Link to={`/claims/${claim.id}`}>{claim.reference}</Link></td><td>{claim.lecturer.name}<small>{claim.lecturer.staffId}</small></td><td>{claim.department.name}</td><td><Status status={claim.status}/></td><td>{claim.decision?.comment??'Awaiting audit decision'}</td></tr>)}</tbody></table></div>:<Empty title="No audit records" message="No claims match this reporting period."/>}</section></>:<Empty title="No audit report" message="No records match this reporting period."/>}</>;}
function FinanceReports(){const [filters,setFilters]=useState({from:'',to:''});const [query,setQuery]=useState(filters);const params=new URLSearchParams(Object.entries(query).filter(([,v])=>v));const result=useResource<{data:FinanceReport}>(()=>api(`/reports/finance?${params}`),[params.toString()]);const data=result.data?.data;return <><PageHeader eyebrow="FINANCE" title="Finance reports" description="Payment obligations, disbursements, outstanding values, and payment exceptions."/><Filters filters={filters} setFilters={setFilters} submit={e=>{e.preventDefault();setQuery(filters);}}/><ErrorNotice message={result.error}/>{result.loading?<Loading/>:data?<><section className="metric-grid"><Metric label="Awaiting payment" value={data.metrics.awaiting}/><Metric label="In processing" value={data.metrics.processing}/><Metric label="Paid claims" value={data.metrics.paid}/><Metric label="Failed payments" value={data.metrics.failed}/></section><section className="workspace-section"><h2>Payment position</h2>{data.totals.length?<div className="table-scroll"><table><thead><tr><th>Currency</th><th>Paid</th><th>Outstanding</th></tr></thead><tbody>{data.totals.map(total=><tr key={total.currency}><td>{total.currency}</td><td>{total.paid}</td><td>{total.outstanding}</td></tr>)}</tbody></table></div>:<Empty title="No payment values" message="Amounts appear after Finance calculates a payment."/>}</section><section className="workspace-section"><h2>Payment register</h2>{data.payments.length?<div className="table-scroll"><table><thead><tr><th>Claim</th><th>Payee</th><th>Department</th><th>Amount</th><th>Status</th><th>Reference</th></tr></thead><tbody>{data.payments.map(item=><tr key={item.id}><td><Link to={`/claims/${item.id}`}>{item.reference}</Link></td><td>{item.lecturer.name}<small>{item.lecturer.staffId}</small></td><td>{item.department.name}</td><td>{item.payment?`${item.payment.currency} ${item.payment.amount}`:'Not calculated'}</td><td><Status status={item.status}/></td><td>{item.payment?.reference??'Not recorded'}</td></tr>)}</tbody></table></div>:<Empty title="No finance records" message="No payment records match this reporting period."/>}</section></>:<Empty title="No finance report" message="No records match this reporting period."/>}</>;}
export function ReportsPage(){const {user}=useAuth();return user!.permissions.includes('reports.view_audit')?<AuditReports/>:user!.permissions.includes('reports.view_finance')?<FinanceReports/>:<Empty title="Reports unavailable" message="This workspace does not have a specialized report view."/>;}
