import { FormEvent, useState } from 'react';
import { Check, Save } from 'lucide-react';
import { api } from '../../services/api';
import { ErrorNotice, Loading, PageHeader, useResource } from '../../components/ui';
const options=[['calendar','Teaching calendar','CONTIGUOUS_FULL_WEEKS','Contiguous full teaching weeks'],['eligibility','Eligibility evidence','VERIFIED_ASSIGNMENTS','Verified lecturer workload assignments'],['overloadAllocation','Overload allocation','FULL_WORKLOAD_SINGLE_CLAIM','All workload in one claim over a common teaching period'],['routing','Department routing','HOME_DEPARTMENT','Lecturer home department'],['coverage','Teaching coverage','SINGLE_ASSIGNMENT_PER_COURSE','One assignment per lecturer, course and semester']] as const;
type Policy={version:number;value:Record<string,string>};
export function ClaimPolicy(){const result=useResource<{data:Policy|null}>(()=>api('/settings/claim-policy'));if(result.loading)return <Loading/>;if(result.error)return <><ErrorNotice message={result.error}/><button className="button secondary" onClick={result.reload}>Retry</button></>;return <PolicyForm key={result.data!.data?.version??0} policy={result.data!.data}/>;}
function PolicyForm({policy}:{policy:Policy|null}){
  const [value,setValue]=useState<Record<string,string>>(policy?.value??{approvalReference:''});const [version,setVersion]=useState(policy?.version??0);const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{const result=await api<{data:Policy}>('/settings/claim-policy',{method:'PUT',body:JSON.stringify({expectedVersion:version,policy:value})});setVersion(result.data.version);setConfirmed(false);setMessage(`Policy version ${result.data.version} recorded.`);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <><PageHeader title="Claim submission policy"/><ErrorNotice message={error}/>{message&&<p className="success-notice" role="status"><Check size={17}/>{message}</p>}<form className="policy-form" onSubmit={save}><label>Institutional approval reference<input required minLength={5} maxLength={200} value={value.approvalReference} onChange={event=>setValue(current=>({...current,approvalReference:event.target.value}))}/></label>{options.map(([key,label,code,name])=><label key={key}>{label}<select required value={value[key]??''} onChange={event=>setValue(current=>({...current,[key]:event.target.value}))}><option value="">Not configured</option><option value={code}>{name}</option></select></label>)}<label className="checkbox-label"><input type="checkbox" required checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>These selections match the approved institutional policy.</label><button className="button primary" disabled={busy||!confirmed}><Save size={16}/>Record policy</button></form></>;
}
