import { FormEvent, useState } from 'react';
import { Pencil, Plus, Save, Search } from 'lucide-react';
import { useAuth } from '../../app/auth';
import { api, patch, post } from '../../services/api';
import { Empty, ErrorNotice, Loading, Modal, PageHeader, Pagination, useResource } from '../../components/ui';

type RecordData={id:string;active:boolean;[key:string]:any};
type Field={key:string;label:string;type?:'number'|'date'|'text';source?:string};
const definitions:Record<string,{name:string;permission:string;fields:Field[]}>= {
  faculties:{name:'Faculties',permission:'faculties.manage',fields:[{key:'code',label:'Code'},{key:'name',label:'Name'}]},
  departments:{name:'Departments',permission:'departments.manage',fields:[{key:'code',label:'Code'},{key:'name',label:'Name'},{key:'facultyId',label:'Faculty',source:'faculties'}]},
  courses:{name:'Courses',permission:'courses.manage',fields:[{key:'code',label:'Code'},{key:'title',label:'Title'},{key:'departmentId',label:'Department',source:'departments'},{key:'creditHours',label:'Credit hours',type:'number'}]},
  'academic-years':{name:'Academic years',permission:'academic_periods.manage',fields:[{key:'name',label:'Name'},{key:'startsOn',label:'Start date',type:'date'},{key:'endsOn',label:'End date',type:'date'}]},
  semesters:{name:'Semesters',permission:'academic_periods.manage',fields:[{key:'name',label:'Name'},{key:'academicYearId',label:'Academic year',source:'academicYears'},{key:'startsOn',label:'Start date',type:'date'},{key:'endsOn',label:'End date',type:'date'}]},
  'workload-rules':{name:'Workload rules',permission:'workloads.manage',fields:[{key:'category',label:'Lecturer category'},{key:'expectedWeeklyHours',label:'Normal weekly hours',type:'text'},{key:'effectiveFrom',label:'Effective from',type:'date'},{key:'effectiveTo',label:'Effective to',type:'date'}]},
  'lecturer-workloads':{name:'Teaching assignments',permission:'workloads.manage',fields:[{key:'lecturerId',label:'Lecturer',source:'lecturers'},{key:'semesterId',label:'Semester',source:'teachingSemesters'},{key:'courseId',label:'Course',source:'teachingCourses'},{key:'weeklyHours',label:'Weekly hours',type:'text'},{key:'weeks',label:'Weeks',type:'number'},{key:'startsOn',label:'Start date',type:'date'},{key:'endsOn',label:'End date',type:'date'}]},
  'payment-rates':{name:'Payment rates',permission:'rates.manage',fields:[{key:'category',label:'Lecturer category'},{key:'employmentType',label:'Employment type'},{key:'semesterId',label:'Semester',source:'teachingSemesters'},{key:'rate',label:'Hourly rate',type:'text'},{key:'currency',label:'Currency'},{key:'roundingPlaces',label:'Rounding places',type:'number'}]},
};
export function ConfigurationPage(){
  const {user}=useAuth();const allowed=Object.entries(definitions).filter(([,definition])=>user!.permissions.includes(definition.permission));
  const [resource,setResource]=useState(allowed[0]?.[0]??'');const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [editing,setEditing]=useState<RecordData|null|undefined>(undefined);
  const list=useResource<{data:RecordData[];meta:{total:number}}>(()=>resource?api(`/configuration/${resource}?page=${page}&pageSize=10&search=${encodeURIComponent(query)}`):Promise.resolve({data:[],meta:{total:0}}),[resource,page,query]);
  const catalog=useResource<{data:Record<string,{id:string;name:string}[]>}>(()=>api('/catalog'));
  if(!allowed.length)return <PageHeader title="Access denied"/>;
  return <><PageHeader title="Academic records" action={<button className="button primary" onClick={()=>setEditing(null)}><Plus size={17}/>Add record</button>}/><div className="toolbar-tabs" role="tablist" aria-label="Academic record type">{allowed.map(([key,definition])=><button key={key} role="tab" aria-selected={key===resource} onClick={()=>{setResource(key);setPage(1);setSearch('');setQuery('');}}>{definition.name}</button>)}</div><form className="search-form list-toolbar" onSubmit={event=>{event.preventDefault();setPage(1);setQuery(search);}}><input aria-label="Search records" placeholder={`Search ${definitions[resource].name.toLowerCase()}`} value={search} onChange={event=>setSearch(event.target.value)}/><button className="button secondary" aria-label="Search" title="Search"><Search size={17}/></button></form><ErrorNotice message={list.error||catalog.error}/>{(list.error||catalog.error)&&<button className="button secondary" onClick={()=>{list.reload();catalog.reload();}}>Retry</button>}{list.loading?<Loading/>:list.data?.data.length?<><div className="table-scroll"><table><thead><tr>{definitions[resource].fields.map(field=><th key={field.key}>{field.label}</th>)}<th>Status</th><th>Edit</th></tr></thead><tbody>{list.data.data.map(record=><tr key={record.id}>{definitions[resource].fields.map(field=><td key={field.key}>{field.source?(catalog.data?.data[field.source]?.find(option=>option.id===record[field.key])?.name??record.faculty?.name??record.department?.name??record.academicYear?.name??'Unavailable'):field.type==='date'?String(record[field.key]).slice(0,10):record[field.key]}</td>)}<td><span className={`status ${record.active!==false?'status-paid':'status-cancelled'}`}>{record.active===undefined?'Recorded':record.active?'Active':'Inactive'}</span></td><td><button className="icon-button" title="Edit record" aria-label={`Edit ${record.name??record.title??record.category??record.lecturer?.name??'assignment'}`} onClick={()=>setEditing(record)}><Pencil size={16}/></button></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={10} total={list.data.meta.total} onPage={setPage}/></>:!list.error&&<Empty title="No records found" message="No academic records match this search."/>}{editing!==undefined&&<RecordEditor resource={resource} record={editing} catalog={catalog.data?.data} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);list.reload();catalog.reload();}}/>}</>;
}
function RecordEditor({resource,record,catalog,close,saved}:{resource:string;record:RecordData|null;catalog?:Record<string,{id:string;name:string}[]>;close:()=>void;saved:()=>void}){
  const definition=definitions[resource];const [form,setForm]=useState<Record<string,any>>(()=>Object.fromEntries([...definition.fields.map(field=>[field.key,record?(field.type==='date'?String(record[field.key]).slice(0,10):record[field.key]):field.type==='number'?3:'']),['active',record?.active??true]]));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [dirty,setDirty]=useState(false);
  function change(key:string,value:unknown){setDirty(true);setForm(current=>({...current,[key]:value}));}
  function dismiss(){if(!busy&&(!dirty||window.confirm('Discard unsaved record changes?')))close();}
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const body=Object.fromEntries(Object.entries(form).filter(([key])=>resource!=='lecturer-workloads'||key!=='active'));if(record)await patch(`/configuration/${resource}/${record.id}`,body);else await post(`/configuration/${resource}`,body);saved();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <Modal title={`${record?'Edit':'Add'} ${definition.name.toLowerCase()} record`} onClose={dismiss}><form onSubmit={submit}><ErrorNotice message={error}/>{definition.fields.map(field=><label key={field.key}>{field.label}{field.source?<select required value={form[field.key]} onChange={event=>change(field.key,event.target.value)}><option value="">Select {field.label.toLowerCase()}</option>{catalog?.[field.source]?.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select>:<input required type={field.type??'text'} min={field.type==='number'?0:undefined} max={field.type==='number'?(field.key==='weeks'?53:30):undefined} step={field.type==='number'?1:undefined} value={form[field.key]} onChange={event=>change(field.key,field.type==='number'?Number(event.target.value):event.target.value)}/>}</label>)}{resource!=='lecturer-workloads'&&<label className="checkbox-label"><input type="checkbox" checked={form.active} onChange={event=>change('active',event.target.checked)}/>Active</label>}<div className="modal-actions"><button className="button secondary" type="button" disabled={busy} onClick={dismiss}>Cancel</button><button className="button primary" disabled={busy||!catalog}><Save size={16}/>{busy?'Saving...':'Save record'}</button></div></form></Modal>;
}
