import { FormEvent, useState } from 'react';
import { Pencil, Plus, Save, Search, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '../../app/auth';
import { api, patch, post } from '../../services/api';
import { ConfirmPrompt, Empty, ErrorNotice, Loading, Modal, PageHeader, Pagination, useResource } from '../../components/ui';

type RecordData={id:string;active:boolean;[key:string]:any};
type Field={key:string;label:string;type?:'number'|'date'|'text';source?:string;options?:{value:string;label:string}[]};
type CatalogOption={id:string;name:string;departmentId?:string|null;departmentName?:string;startsOn?:string;endsOn?:string};
type Catalog=Record<string,CatalogOption[]>;
const definitions:Record<string,{name:string;permission:string;fields:Field[]}>= {
  faculties:{name:'Faculties',permission:'faculties.manage',fields:[{key:'code',label:'Code'},{key:'name',label:'Name'}]},
  departments:{name:'Departments',permission:'departments.manage',fields:[{key:'code',label:'Code'},{key:'name',label:'Name'},{key:'facultyId',label:'Faculty',source:'faculties'}]},
  courses:{name:'Courses',permission:'courses.manage',fields:[{key:'code',label:'Code'},{key:'title',label:'Title'},{key:'departmentId',label:'Department',source:'departments'},{key:'creditHours',label:'Credit hours',type:'number'}]},
  'academic-years':{name:'Academic years',permission:'academic_periods.manage',fields:[{key:'name',label:'Name'},{key:'startsOn',label:'Start date',type:'date'},{key:'endsOn',label:'End date',type:'date'}]},
  semesters:{name:'Semesters',permission:'academic_periods.manage',fields:[{key:'name',label:'Name'},{key:'academicYearId',label:'Academic year',source:'academicYears'},{key:'startsOn',label:'Start date',type:'date'},{key:'endsOn',label:'End date',type:'date'}]},
  'workload-rules':{name:'Workload rules',permission:'workloads.manage',fields:[{key:'category',label:'Lecturer category'},{key:'expectedWeeklyHours',label:'Normal weekly hours',type:'number'},{key:'effectiveFrom',label:'Effective from',type:'date'},{key:'effectiveTo',label:'Effective to',type:'date'}]},
  'lecturer-workloads':{name:'Teaching assignments',permission:'workloads.manage',fields:[{key:'lecturerId',label:'Lecturer',source:'lecturers'},{key:'semesterId',label:'Semester',source:'teachingSemesters'},{key:'courseId',label:'Course',source:'teachingCourses'},{key:'weeklyHours',label:'Weekly hours',type:'number'},{key:'weeks',label:'Weeks',type:'number'},{key:'startsOn',label:'Start date',type:'date'},{key:'endsOn',label:'End date',type:'date'}]},
  'payment-rates':{name:'Payment rates',permission:'rates.manage',fields:[{key:'category',label:'Lecturer category'},{key:'employmentType',label:'Employment type',options:[{value:'PART_TIME',label:'Part time'},{value:'FULL_TIME',label:'Full time'}]},{key:'semesterId',label:'Semester',source:'teachingSemesters'},{key:'rate',label:'Hourly rate',type:'number'},{key:'currency',label:'Currency'},{key:'roundingPlaces',label:'Rounding places',type:'number'}]},
};
export function ConfigurationPage(){
  const {user}=useAuth();const allowed=Object.entries(definitions).filter(([,definition])=>user!.permissions.includes(definition.permission));
  const [params]=useSearchParams();const requestedResource=params.get('section')??'';const resource=allowed.some(([key])=>key===requestedResource)?requestedResource:allowed[0]?.[0]??'';const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [editing,setEditing]=useState<RecordData|null|undefined>(undefined);const [message,setMessage]=useState('');
  const list=useResource<{data:RecordData[];meta:{total:number}}>(()=>resource?api(`/configuration/${resource}?page=${page}&pageSize=10&search=${encodeURIComponent(query)}`):Promise.resolve({data:[],meta:{total:0}}),[resource,page,query]);
  const catalog=useResource<{data:Catalog}>(()=>api('/catalog'));
  if(!allowed.length)return <PageHeader title="Access denied"/>;
  return <><PageHeader title={definitions[resource].name} action={<button className="button primary" disabled={catalog.loading||!!catalog.error} onClick={()=>setEditing(null)}><Plus size={17}/>Add record</button>}/>{message&&<p className="success-notice" role="status">{message}</p>}<form className="search-form list-toolbar" onSubmit={event=>{event.preventDefault();setPage(1);setQuery(search);}}><input aria-label="Search records" placeholder={`Search ${definitions[resource].name.toLowerCase()}`} value={search} onChange={event=>setSearch(event.target.value)}/><button className="button secondary" aria-label="Search" title="Search"><Search size={17}/></button></form><ErrorNotice message={list.error||catalog.error}/>{(list.error||catalog.error)&&<button className="button secondary" onClick={()=>{list.reload();catalog.reload();}}>Retry</button>}{list.loading?<Loading/>:list.data?.data.length?<><div className="table-scroll"><table><thead><tr>{definitions[resource].fields.map(field=><th key={field.key}>{field.label}</th>)}<th>Status</th><th>Edit</th></tr></thead><tbody>{list.data.data.map(record=><tr key={record.id}>{definitions[resource].fields.map(field=><td key={field.key}>{field.source?(catalog.data?.data[field.source]?.find(option=>option.id===record[field.key])?.name??record.faculty?.name??record.department?.name??record.academicYear?.name??'Unavailable'):field.type==='date'?String(record[field.key]).slice(0,10):record[field.key]}</td>)}<td><span className={`status ${record.active!==false?'status-paid':'status-cancelled'}`}>{record.active===undefined?'Recorded':record.active?'Active':'Inactive'}</span></td><td><button className="icon-button" title="Edit record" aria-label={`Edit ${record.name??record.title??record.category??record.lecturer?.name??'assignment'}`} onClick={()=>setEditing(record)}><Pencil size={16}/></button></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={10} total={list.data.meta.total} onPage={setPage}/></>:!list.error&&<Empty title="No records found" message="No academic records match this search."/>}{editing!==undefined&&<RecordEditor resource={resource} record={editing} catalog={catalog.data?.data} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);setMessage(`${definitions[resource].name.slice(0,-1)} record saved successfully.`);list.reload();catalog.reload();}}/>}</>;
}
function RecordEditor({resource,record,catalog,close,saved}:{resource:string;record:RecordData|null;catalog?:Catalog;close:()=>void;saved:()=>void}){
  const definition=definitions[resource];const [form,setForm]=useState<Record<string,any>>(()=>Object.fromEntries([...definition.fields.map(field=>[field.key,record?(field.type==='date'?String(record[field.key]).slice(0,10):record[field.key]):field.key==='currency'?'GHS':field.type==='number'?3:'']),['active',record?.active??true]]));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [dirty,setDirty]=useState(false);const [confirmDiscard,setConfirmDiscard]=useState(false);
  const lecturer=catalog?.lecturers?.find(option=>option.id===form.lecturerId);
  const semester=catalog?.teachingSemesters?.find(option=>option.id===form.semesterId);
  const courseOptions=resource==='lecturer-workloads'&&lecturer?.departmentId?(catalog?.teachingCourses??[]).filter(option=>option.departmentId===lecturer.departmentId):resource==='lecturer-workloads'?[]:undefined;
  const dateOnly=(value?:string)=>value?.slice(0,10)??'';
  function assignmentDefaults(selectedSemester:CatalogOption){
    const startsOn=dateOnly(selectedSemester.startsOn);const endsOn=dateOnly(selectedSemester.endsOn);const days=Math.floor((Date.parse(endsOn)-Date.parse(startsOn))/86400000)+1;const weeks=Math.floor(days/7);
    return {startsOn,endsOn:weeks?new Date(Date.parse(startsOn)+(weeks*7-1)*86400000).toISOString().slice(0,10):endsOn,weeks:weeks||1};
  }
  function change(key:string,value:unknown){setDirty(true);setForm(current=>{const next={...current,[key]:value};if(resource==='lecturer-workloads'&&key==='lecturerId'){const selected=catalog?.lecturers?.find(option=>option.id===value);const selectedCourse=catalog?.teachingCourses?.find(option=>option.id===current.courseId);if(selectedCourse&&selected?.departmentId!==selectedCourse.departmentId)next.courseId='';}if(resource==='lecturer-workloads'&&key==='semesterId'){const selected=catalog?.teachingSemesters?.find(option=>option.id===value);if(selected)Object.assign(next,assignmentDefaults(selected));}return next;});}
  function dismiss(){if(busy)return;if(dirty){setConfirmDiscard(true);return;}close();}
  async function submit(event:FormEvent){event.preventDefault();if(resource==='lecturer-workloads'&&!lecturer?.departmentId){setError('Assign the lecturer to a department in Staff accounts before creating a teaching assignment.');return;}if(resource==='lecturer-workloads'&&!courseOptions?.length){setError('Create or activate a course in the lecturer\'s department before creating a teaching assignment.');return;}setBusy(true);setError('');try{const body=Object.fromEntries(Object.entries(form).filter(([key])=>resource!=='lecturer-workloads'||key!=='active'));if(record)await patch(`/configuration/${resource}/${record.id}`,body);else await post(`/configuration/${resource}`,body);saved();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <><Modal title={`${record?'Edit':'Add'} ${definition.name.toLowerCase()} record`} onClose={dismiss}><form onSubmit={submit}><ErrorNotice message={error}/>{definition.fields.map(field=>{const options=field.key==='courseId'?courseOptions:field.source?catalog?.[field.source]:field.options?.map(option=>({id:option.value,name:option.label}));const isCourse=field.key==='courseId'&&resource==='lecturer-workloads';const isSelect=Boolean(field.source||field.options);const dateBound=field.type==='date'&&semester?{min:dateOnly(semester.startsOn),max:dateOnly(semester.endsOn)}:{};const hourlyField=field.key==='weeklyHours'||field.key==='expectedWeeklyHours';return <label key={field.key}>{field.label}{isSelect?<select required disabled={isCourse&&!lecturer?.departmentId} value={form[field.key]} onChange={event=>change(field.key,event.target.value)}><option value="">{isCourse&&!lecturer?'Select a lecturer first':isCourse&&!options?.length?'No active courses in this department':`Select ${field.label.toLowerCase()}`}</option>{options?.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select>:<input required type={field.type??'text'} min={field.type==='number'?(hourlyField?0.25:0):dateBound.min} max={field.type==='number'?(field.key==='weeks'?53:hourlyField?168:undefined):dateBound.max} step={field.type==='number'?(hourlyField?0.25:1):undefined} value={form[field.key]} onChange={event=>change(field.key,field.type==='number'?Number(event.target.value):field.key==='currency'?event.target.value.toUpperCase():event.target.value)}/>} {isCourse&&lecturer&&<small>Courses are limited to {lecturer.departmentName??'the lecturer\'s department'}.</small>}{field.key==='semesterId'&&resource==='lecturer-workloads'&&<small>Choosing a semester fills a valid teaching period and number of full weeks automatically.</small>}</label>;})}{resource!=='lecturer-workloads'&&<label className="checkbox-label"><input type="checkbox" checked={form.active} onChange={event=>change('active',event.target.checked)}/>Active</label>}<div className="modal-actions"><button className="button secondary" type="button" disabled={busy} onClick={dismiss}><X size={16}/>Cancel</button><button className="button primary" type="submit" disabled={busy||!catalog}><Save size={16}/>{busy?'Saving...':'Save record'}</button></div></form></Modal><ConfirmPrompt open={confirmDiscard} title="Discard record changes?" message="The information entered in this academic record has not been saved." onCancel={()=>setConfirmDiscard(false)} onConfirm={close}/></>;
}
