import { FormEvent, useState } from 'react';
import { KeyRound, Pencil, Plus, Save, Search, ShieldCheck, Upload } from 'lucide-react';
import { roleNames, useAuth } from '../../app/auth';
import { api, patch, post } from '../../services/api';
import { Empty, ErrorNotice, Loading, Modal, PageHeader, Pagination, useResource } from '../../components/ui';

interface Staff {id:string;name:string;email:string;staffId:string;title:string;employmentType:string;category:string;active:boolean;departmentId:string|null;department:{name:string}|null;roles:{role:{code:string;name:string}}[];scopes:{roleCode:string;departmentId:string}[];}
interface Catalog {departments:{id:string;name:string}[];}
interface StaffForm {name:string;email:string;staffId:string;title:string;employmentType:string;category:string;active:boolean;departmentId:string;password:string;}
const blank:StaffForm={name:'',email:'',staffId:'',title:'Lecturer',employmentType:'PART_TIME',category:'LECTURER',active:true,departmentId:'',password:''};

export function UsersPage(){
  const {user}=useAuth();const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [editing,setEditing]=useState<Staff|null|undefined>(undefined);const [importing,setImporting]=useState(false);const [roleUser,setRoleUser]=useState<Staff|null>(null);const [resetUser,setResetUser]=useState<Staff|null>(null);const [resetUrl,setResetUrl]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const list=useResource<{data:Staff[];meta:{total:number}}>(()=>api(`/users?page=${page}&pageSize=10&search=${encodeURIComponent(query)}`),[page,query]);
  const catalog=useResource<{data:Catalog}>(()=>api('/catalog'));
  async function reset(){setBusy(true);setError('');try{const result=await post(`/users/${resetUser!.id}/reset-access`);setResetUrl(result.data.resetUrl);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <><PageHeader title="Staff accounts" action={<div className="claim-detail-actions"><button className="button secondary" onClick={()=>setImporting(true)}><Upload size={17}/>Import CSV</button><button className="button primary" onClick={()=>setEditing(null)}><Plus size={17}/>Add staff</button></div>}/><form className="search-form list-toolbar" onSubmit={event=>{event.preventDefault();setPage(1);setQuery(search);}}><input aria-label="Search staff" placeholder="Name, staff ID or email" value={search} onChange={event=>setSearch(event.target.value)}/><button className="button secondary" title="Search" aria-label="Search"><Search size={17}/></button></form><ErrorNotice message={list.error||catalog.error}/>{(list.error||catalog.error)&&<button className="button secondary" onClick={()=>{list.reload();catalog.reload();}}>Retry</button>}{list.loading?<Loading/>:list.data?.data.length?<><div className="table-scroll"><table><thead><tr><th>Staff member</th><th>Department</th><th>Roles</th><th>Status</th><th>Actions</th></tr></thead><tbody>{list.data.data.map(staff=><tr key={staff.id}><td><strong>{staff.name}</strong><small>{staff.staffId}</small><small>{staff.email}</small></td><td>{staff.department?.name??'University administration'}</td><td>{staff.roles.map(item=>item.role.name).join(', ')||'Unassigned'}</td><td><span className={`status ${staff.active?'status-paid':'status-cancelled'}`}>{staff.active?'Active':'Inactive'}</span></td><td><div className="record-actions"><button className="icon-button" title="Edit account" aria-label={`Edit ${staff.name}`} onClick={()=>setEditing(staff)}><Pencil size={16}/></button>{user!.permissions.includes('roles.manage')&&<button className="icon-button" disabled={staff.id===user!.id} title="Roles and departments" aria-label={`Roles for ${staff.name}`} onClick={()=>setRoleUser(staff)}><ShieldCheck size={16}/></button>}<button className="icon-button" title="Reset access" aria-label={`Reset access for ${staff.name}`} onClick={()=>{setResetUser(staff);setResetUrl('');setError('');}}><KeyRound size={16}/></button></div></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={10} total={list.data.meta.total} onPage={setPage}/></>:!list.error&&<Empty title="No staff found" message="No accounts match this search."/>}
  {editing!==undefined&&<StaffEditor staff={editing} catalog={catalog.data?.data} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);list.reload();}}/>}
  {importing&&<StaffImport catalog={catalog.data?.data} close={()=>setImporting(false)} imported={()=>{setImporting(false);list.reload();}}/>}
  {roleUser&&<RoleEditor staff={roleUser} catalog={catalog.data?.data} close={()=>setRoleUser(null)} saved={()=>{setRoleUser(null);list.reload();}}/>}
  {resetUser&&<Modal title={`Reset access: ${resetUser.name}`} onClose={()=>{if(!busy)setResetUser(null);}}><ErrorNotice message={error}/>{resetUrl?<><label>Reset link<input readOnly value={resetUrl} onFocus={event=>event.target.select()}/></label><p className="dialog-note">Expires in 30 minutes. Existing sessions have been revoked.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setResetUser(null)}>Close</button></div></>:<><p className="dialog-note">Issue a single-use password reset link and sign this account out of all sessions?</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setResetUser(null)}>Cancel</button><button className="button primary" disabled={busy} onClick={reset}><KeyRound size={16}/>Issue reset link</button></div></>}</Modal>}</>;
}

function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(line=>line.trim());const parseLine=(line:string)=>{const cells:string[]=[];let cell='';let quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){cells.push(cell.trim());cell='';}else cell+=ch;}cells.push(cell.trim());return cells;};const [head,...rows]=lines.map(parseLine);return rows.map(row=>Object.fromEntries(head.map((key,index)=>[key.trim(),row[index]??''])));}
function StaffImport({catalog,close,imported}:{catalog?:Catalog;close:()=>void;imported:()=>void}){
  const {user}=useAuth();
  const [csv,setCsv]=useState('');const [defaultPassword,setDefaultPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const sampleCsv='name,email,staffId,title,employmentType,category,department,roles,password,active\nAma Mensah,ama.mensah@upsa.edu.gh,UPS-9001,Lecturer,PART_TIME,LECTURER,Accounting,LECTURER,,true';
  const canAssignRoles=Boolean(user?.permissions.includes('roles.manage'));
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const departmentByName=new Map(catalog?.departments.map(department=>[department.name.toLowerCase(),department.id])??[]);const users=parseCsv(csv).map(row=>({name:row.name,email:row.email,staffId:row.staffId,title:row.title||'Lecturer',employmentType:(row.employmentType||'PART_TIME').toUpperCase().replace(' ','_'),category:row.category||'LECTURER',active:row.active?row.active.toLowerCase()!=='false':true,departmentId:row.departmentId||departmentByName.get((row.department||'').toLowerCase())||null,password:row.password||undefined,roles:(row.roles||'LECTURER').split(/[|;]/).map(role=>role.trim().toUpperCase().replace(' ','_')).filter(Boolean)}));await post('/users/import',{defaultPassword:defaultPassword||undefined,users});imported();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <Modal title="Import staff from CSV" onClose={()=>{if(!busy)close();}}><form onSubmit={submit}><ErrorNotice message={error}/><p className="dialog-note">CSV headers: name,email,staffId,title,employmentType,category,department,roles,password,active. Separate multiple roles with semicolons.</p><p className="dialog-note">{canAssignRoles?'Scoped roles such as HOD, Pro VC, Finance, and Auditor must include a department.':'Your account can bulk-create lecturer accounts. Administrators can import HOD, Pro VC, Finance, Auditor, and Admin roles.'}</p><button type="button" className="button secondary" disabled={busy} onClick={()=>setCsv(sampleCsv)}>Use sample CSV</button><label>CSV file<input type="file" accept=".csv,text/csv" disabled={busy} onChange={async event=>{const file=event.target.files?.[0];if(file)setCsv(await file.text());}}/></label><label>CSV content<textarea required value={csv} onChange={event=>setCsv(event.target.value)} placeholder="name,email,staffId,title,employmentType,category,department,roles,password,active"/></label><label>Default password<input type="password" minLength={12} maxLength={72} value={defaultPassword} onChange={event=>setDefaultPassword(event.target.value)} placeholder="Used when a row has no password"/></label><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={close}>Close</button><button className="button primary" disabled={busy||!catalog}><Upload size={16}/>{busy?'Importing...':'Import staff'}</button></div></form></Modal>;
}

function StaffEditor({staff,catalog,close,saved}:{staff:Staff|null;catalog?:Catalog;close:()=>void;saved:()=>void}){
  const [form,setForm]=useState<StaffForm>(staff?{name:staff.name,email:staff.email,staffId:staff.staffId,title:staff.title,employmentType:staff.employmentType,category:staff.category,active:staff.active,departmentId:staff.departmentId??'',password:''}:blank);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);
  function change(field:keyof StaffForm,value:string|boolean){setDirty(true);setForm(current=>({...current,[field]:value}));}
  function dismiss(){if(!busy&&(!dirty||window.confirm('Discard unsaved account changes?')))close();}
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const {password,...fields}=form;const body={...fields,departmentId:form.departmentId||null,...(password?{password}:{})};if(staff)await patch(`/users/${staff.id}`,body);else await post('/users',body);saved();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <Modal title={staff?'Edit staff account':'Add staff account'} onClose={dismiss}><form onSubmit={submit}><ErrorNotice message={error}/><div className="form-grid">{(['name','email','staffId','title','category'] as const).map(field=><label key={field}>{({name:'Full name',email:'Email',staffId:'Staff ID',title:'Title',category:'Lecturer category'})[field]}<input required={field!=='title'} type={field==='email'?'email':'text'} value={form[field]} onChange={event=>change(field,event.target.value)}/></label>)}<label>Employment<select value={form.employmentType} onChange={event=>change('employmentType',event.target.value)}><option value="PART_TIME">Part time</option><option value="FULL_TIME">Full time</option></select></label><label className="full-width">Department<select value={form.departmentId} onChange={event=>change('departmentId',event.target.value)} disabled={!catalog}><option value="">University administration</option>{catalog?.departments.map(department=><option key={department.id} value={department.id}>{department.name}</option>)}</select></label>{!staff&&<label className="full-width">Initial password<input required type="password" autoComplete="new-password" minLength={12} maxLength={72} value={form.password} onChange={event=>change('password',event.target.value)}/></label>}<label className="checkbox-label"><input type="checkbox" checked={form.active} onChange={event=>change('active',event.target.checked)}/>Active account</label></div><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={dismiss}>Cancel</button><button className="button primary" disabled={busy||!catalog}><Save size={16}/>{busy?'Saving...':'Save account'}</button></div></form></Modal>;
}

function RoleEditor({staff,catalog,close,saved}:{staff:Staff;catalog?:Catalog;close:()=>void;saved:()=>void}){
  const [roles,setRoles]=useState(staff.roles.map(item=>item.role.code));const [scopes,setScopes]=useState(staff.scopes);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [dirty,setDirty]=useState(false);
  function dismiss(){if(!busy&&(!dirty||window.confirm('Discard unsaved role changes?')))close();}
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await api(`/users/${staff.id}/roles`,{method:'PUT',body:JSON.stringify({roles,scopes:scopes.filter(scope=>roles.includes(scope.roleCode))})});saved();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <Modal title={`Roles: ${staff.name}`} onClose={dismiss}><form onSubmit={submit}><ErrorNotice message={error}/><fieldset><legend>Assigned roles</legend>{Object.entries(roleNames).map(([code,name])=><label key={code} className="checkbox-label"><input type="checkbox" checked={roles.includes(code)} onChange={event=>{setDirty(true);setRoles(current=>event.target.checked?[...current,code]:current.filter(role=>role!==code));}}/>{name}</label>)}</fieldset>{roles.filter(role=>['HOD','PRO_VC','FINANCE','AUDITOR'].includes(role)).map(role=><fieldset key={role}><legend>{roleNames[role]} departments</legend>{catalog?.departments.map(department=><label key={department.id} className="checkbox-label"><input type="checkbox" checked={scopes.some(scope=>scope.roleCode===role&&scope.departmentId===department.id)} onChange={event=>{setDirty(true);setScopes(current=>event.target.checked?[...current,{roleCode:role,departmentId:department.id}]:current.filter(scope=>!(scope.roleCode===role&&scope.departmentId===department.id)));}}/>{department.name}</label>)}</fieldset>)}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={dismiss}>Cancel</button><button className="button primary" disabled={busy||!roles.length||!catalog}><ShieldCheck size={16}/>Save roles</button></div></form></Modal>;
}
