import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';

export async function testClaims({db,request,login,adminToken,hod}){
  const owner=await login('lecturer@example.test');const token=owner.body.data.accessToken;
  const stranger=await login('other-lecturer@example.test');
  await db.user.update({where:{id:hod.body.data.user.id},data:{active:true}});
  await db.scopeGrant.updateMany({where:{userId:hod.body.data.user.id},data:{validFrom:new Date('2020-01-01'),validTo:null}});
  const semester=await db.semester.findFirstOrThrow();const course=await db.course.findFirstOrThrow();
  const item={courseId:course.id,startsOn:'2026-09-07',endsOn:'2026-10-04',weeklyHours:'2.5',weeks:4,remarks:'Synthetic integration fixture'};
  const body={semesterId:semester.id,type:'PART_TIME',items:[item],remarks:'TEST ONLY'};
  const key=randomUUID();
  const created=await request('/claims',{token,method:'POST',body,key});assert.equal(created.status,201);
  const id=created.body.data.id;
  const replay=await request('/claims',{token,method:'POST',body,key});assert.equal(replay.body.data.id,id);
  assert.equal((await request('/claims',{token,method:'POST',body:{...body,remarks:'Changed'},key})).status,409);
  assert.equal((await request('/claims',{token,method:'POST',body:{...body,totalHours:'999'},key:randomUUID()})).status,400);
  assert.equal((await request(`/claims/${id}`,{token:stranger.body.data.accessToken})).status,404);
  assert.equal((await request(`/claims/${id}`,{token:hod.body.data.accessToken})).status,404);
  assert.equal((await request(`/claims/${id}`,{token:adminToken})).status,200);
  assert.equal((await request(`/claims/${id}`,{token:stranger.body.data.accessToken,method:'PATCH',body:{...body,expectedVersion:1}})).status,404);
  const updates=await Promise.all([request(`/claims/${id}`,{token,method:'PATCH',body:{...body,expectedVersion:1}}),request(`/claims/${id}`,{token,method:'PATCH',body:{...body,expectedVersion:1}})]);
  assert.deepEqual(updates.map(result=>result.status).sort(),[200,409]);
  const detail=await request(`/claims/${id}`,{token});assert.equal(detail.body.data.totalHours,'10');assert.equal(detail.body.data.version,2);
  const submissionKey=randomUUID();
  assert.equal((await request(`/claims/${id}/submit`,{token,method:'POST',body:{expectedVersion:2},key:submissionKey})).status,422);
  assert.equal(await db.claimRevision.count({where:{claimId:id}}),0);
  const policy={approvalReference:'SYNTHETIC TEST FIXTURE ONLY',calendar:'CONTIGUOUS_FULL_WEEKS',eligibility:'VERIFIED_ASSIGNMENTS',overloadAllocation:'FULL_WORKLOAD_SINGLE_CLAIM',routing:'HOME_DEPARTMENT',coverage:'SINGLE_ASSIGNMENT_PER_COURSE'};
  assert.equal((await request('/settings/claim-policy',{token,method:'PUT',body:{expectedVersion:0,policy}})).status,403);
  assert.equal((await request('/settings/claim-policy',{token:adminToken,method:'PUT',body:{expectedVersion:0,policy}})).status,200);
  assert.equal((await request(`/claims/${id}/submit`,{token,method:'POST',body:{expectedVersion:2},key:submissionKey})).status,422);
  const assignment={lecturerId:owner.body.data.user.id,semesterId:semester.id,courseId:course.id,startsOn:item.startsOn,endsOn:item.endsOn,weeklyHours:item.weeklyHours,weeks:item.weeks};
  const workload=await request('/configuration/lecturer-workloads',{token:adminToken,method:'POST',body:assignment});assert.equal(workload.status,201);
  const submitted=await request(`/claims/${id}/submit`,{token,method:'POST',body:{expectedVersion:2},key:submissionKey});assert.equal(submitted.status,201,JSON.stringify(submitted.body));assert.equal(submitted.body.data.status,'HOD_REVIEW');
  assert.equal((await request(`/claims/${id}/submit`,{token,method:'POST',body:{expectedVersion:2},key:submissionKey})).status,201);
  assert.equal(await db.claimRevision.count({where:{claimId:id}}),1);
  await db.course.update({where:{id:course.id},data:{title:'Renamed after submission'}});
  await db.user.update({where:{id:owner.body.data.user.id},data:{name:'Renamed after submission'}});
  const historical=await request(`/claims/${id}`,{token});
  assert.deepEqual(historical.body.data.history.slice(-2).map(event=>event.toStatus),['SUBMITTED','HOD_REVIEW']);
  assert.equal(historical.body.data.lecturer.name,owner.body.data.user.name);
  assert.equal(historical.body.data.items[0].course.title,course.title);
  assert.equal((await request(`/claims/${id}`,{token:hod.body.data.accessToken})).status,200);
  const approvedByHod=await request(`/claims/${id}/hod-decision`,{token:hod.body.data.accessToken,method:'POST',body:{expectedVersion:3,decision:'APPROVE',comment:'HOD verified and approved for VC final review.'}});
  assert.equal(approvedByHod.status,201,JSON.stringify(approvedByHod.body));assert.equal(approvedByHod.body.data.status,'PRO_VC_REVIEW');
  assert.equal(await db.approval.count({where:{claimId:id,revision:1,stage:'HOD',decision:'APPROVE'}}),1);
  const adminUser=await db.user.findUniqueOrThrow({where:{email:'admin@example.test'}});
  for(const code of ['PRO_VC','FINANCE']){
    const role=await db.role.findUniqueOrThrow({where:{code}});
    await db.userRole.upsert({where:{userId_roleId:{userId:adminUser.id,roleId:role.id}},create:{userId:adminUser.id,roleId:role.id},update:{}});
    await db.scopeGrant.create({data:{userId:adminUser.id,roleCode:code,departmentId:owner.body.data.user.departmentId}});
  }
  assert.equal((await request(`/claims/${id}`,{token:adminToken})).status,200);
  assert.equal((await request(`/claims/${id}/provc-decision`,{token:hod.body.data.accessToken,method:'POST',body:{expectedVersion:4,decision:'APPROVE',comment:'HOD cannot final approve'}})).status,403);
  assert.equal((await request(`/claims/${id}/provc-decision`,{token:adminToken,method:'POST',body:{expectedVersion:3,decision:'APPROVE',comment:'Stale final decision'}})).status,409);
  const approvedByProVc=await request(`/claims/${id}/provc-decision`,{token:adminToken,method:'POST',body:{expectedVersion:4,decision:'APPROVE',comment:'Final authorization granted before audit.'}});assert.equal(approvedByProVc.status,201,JSON.stringify(approvedByProVc.body));assert.equal(approvedByProVc.body.data.status,'AUDIT_REVIEW');
  assert.equal((await request(`/claims/${id}/provc-decision`,{token:adminToken,method:'POST',body:{expectedVersion:4,decision:'REJECT',comment:'Duplicate final decision'}})).status,409);
  assert.equal(await db.approval.count({where:{claimId:id,revision:1,stage:'PRO_VC',decision:'APPROVE'}}),1);
  const seedAuditor=await db.user.findUniqueOrThrow({where:{email:'auditor@example.test'}});
  for(let attempt=0;attempt<80&&!await db.notification.count({where:{claimId:id,recipientId:seedAuditor.id,title:'Claim approved by VC'}});attempt++)await new Promise(resolve=>setTimeout(resolve,250));
  assert.equal(await db.notification.count({where:{claimId:id,recipientId:seedAuditor.id,title:'Claim approved by VC'}}),1);
  const auditor=await login('auditor@example.test');
  const auditCleared=await request(`/claims/${id}/audit-decision`,{token:auditor.body.data.accessToken,method:'POST',body:{expectedVersion:5,decision:'CLEAR',reason:'Audit cleared',comment:'Evidence verified and compliant.'}});
  assert.equal(auditCleared.status,201,JSON.stringify(auditCleared.body));assert.equal(auditCleared.body.data.status,'AUDIT_CLEARED');
  const financeUser=await db.user.findUniqueOrThrow({where:{email:'finance@example.test'}});
  for(let attempt=0;attempt<80&&!await db.notification.count({where:{claimId:id,recipientId:financeUser.id,title:'Claim cleared by Audit'}});attempt++)await new Promise(resolve=>setTimeout(resolve,250));
  assert.equal(await db.notification.count({where:{claimId:id,recipientId:financeUser.id,title:'Claim cleared by Audit'}}),1);
  assert.equal((await request(`/claims/${id}/finance-start`,{token:hod.body.data.accessToken,method:'POST',body:{expectedVersion:6}})).status,403);
  const financeStarted=await request(`/claims/${id}/finance-start`,{token:adminToken,method:'POST',body:{expectedVersion:6}});assert.equal(financeStarted.status,201,JSON.stringify(financeStarted.body));assert.equal(financeStarted.body.data.status,'FINANCE_PROCESSING');
  assert.equal((await request(`/claims/${id}/payment-pending`,{token:adminToken,method:'POST',body:{expectedVersion:7}})).status,422);
  const rate=await request('/configuration/payment-rates',{token:adminToken,method:'POST',body:{category:'LECTURER',employmentType:'PART_TIME',semesterId:semester.id,rate:'25.5',currency:'GHS',roundingPlaces:2,active:true}});assert.equal(rate.status,201,JSON.stringify(rate.body));
  const pending=await request(`/claims/${id}/payment-pending`,{token:adminToken,method:'POST',body:{expectedVersion:7}});assert.equal(pending.status,201,JSON.stringify(pending.body));assert.equal(pending.body.data.status,'PAYMENT_PENDING');assert.equal(pending.body.data.payment.amount,'255');
  assert.equal((await request(`/claims/${id}/payment-pending`,{token:adminToken,method:'POST',body:{expectedVersion:7}})).status,409);
  const paid=await request(`/claims/${id}/payment-complete`,{token:adminToken,method:'POST',body:{expectedVersion:8,paymentVersion:1,reference:'EXT-PAY-001',paidOn:'2026-11-15',notes:'Synthetic payment fixture'}});assert.equal(paid.status,201,JSON.stringify(paid.body));assert.equal(paid.body.data.status,'PAID');
  assert.equal((await request(`/claims/${id}/payment-complete`,{token:adminToken,method:'POST',body:{expectedVersion:8,paymentVersion:1,reference:'EXT-PAY-002',paidOn:'2026-11-15',notes:''}})).status,409);
  assert.equal(await db.payment.count({where:{claimId:id,status:'PAID',reference:'EXT-PAY-001'}}),1);
  const auditorRole=await db.role.findUniqueOrThrow({where:{code:'AUDITOR'}});
  await db.userRole.upsert({where:{userId_roleId:{userId:stranger.body.data.user.id,roleId:auditorRole.id}},create:{userId:stranger.body.data.user.id,roleId:auditorRole.id},update:{}});
  await db.scopeGrant.create({data:{userId:stranger.body.data.user.id,roleCode:'AUDITOR',departmentId:owner.body.data.user.departmentId}});
  const auditSearch=await request('/audit-logs?search=PAYMENT_COMPLETED',{token:stranger.body.data.accessToken});assert.equal(auditSearch.status,200,JSON.stringify(auditSearch.body));assert(auditSearch.body.data.some(event=>event.action==='PAYMENT_COMPLETED'));
  const adminAudit=await request('/audit-logs?search=CLAIM_SUBMITTED',{token:adminToken});assert.equal(adminAudit.status,200,JSON.stringify(adminAudit.body));assert(adminAudit.body.meta.total>=1);
  assert.equal((await request('/audit-logs',{token})).status,403);
  const ownReport=await request('/reports/summary',{token});assert.equal(ownReport.status,200,JSON.stringify(ownReport.body));assert.equal(ownReport.body.data.counts.PAID,1);assert.equal(ownReport.body.data.paidTotals.GHS,'255.0000');
  const financeReport=await request('/reports/summary?status=PAID',{token:adminToken});assert.equal(financeReport.status,200,JSON.stringify(financeReport.body));assert.equal(financeReport.body.data.totalClaims,1);assert.equal(financeReport.body.data.recent[0].reference,historical.body.data.reference);
  assert.equal((await request(`/claims/${id}`,{token,method:'PATCH',body:{...body,expectedVersion:3}})).status,409);
  const duplicate=await request('/claims',{token,method:'POST',body,key:randomUUID()});assert.equal(duplicate.status,201);
  assert.equal((await request(`/claims/${duplicate.body.data.id}/submit`,{token,method:'POST',body:{expectedVersion:1},key:randomUUID()})).status,409);
  assert.equal((await db.claim.findUnique({where:{id:duplicate.body.data.id}})).status,'DRAFT');
  assert.equal(await db.claimRevision.count({where:{claimId:duplicate.body.data.id}}),0);
  assert.equal((await request(`/configuration/lecturer-workloads/${workload.body.data.id}`,{token:adminToken,method:'PATCH',body:assignment})).status,409);
  const revision=await db.claimRevision.findFirstOrThrow({where:{claimId:id}});
  await assert.rejects(()=>db.claimRevision.update({where:{id:revision.id},data:{snapshot:{tampered:true}}}));
  await assert.rejects(()=>db.auditLog.updateMany({where:{entityId:id},data:{action:'TAMPERED'}}));
  for(let attempt=0;attempt<80&&!await db.notification.count({where:{claimId:id}});attempt++)await new Promise(resolve=>setTimeout(resolve,250));
  const provcUser=await db.user.findUniqueOrThrow({where:{email:'provc@example.test'}});
  assert.equal(await db.notification.count({where:{claimId:id,recipientId:provcUser.id}}),1);
  await db.outboxEvent.updateMany({where:{aggregateId:id},data:{deliveredAt:null}});
  for(let attempt=0;attempt<80&&await db.outboxEvent.count({where:{aggregateId:id,deliveredAt:null}});attempt++)await new Promise(resolve=>setTimeout(resolve,250));
  assert.equal(await db.notification.count({where:{claimId:id,recipientId:provcUser.id,title:'Claim approved by HOD'}}),1);
  assert.equal((await request(`/claims/${duplicate.body.data.id}/cancel`,{token,method:'POST',body:{expectedVersion:1}})).status,201);
  assert.equal((await request(`/claims/${duplicate.body.data.id}/cancel`,{token,method:'POST',body:{expectedVersion:1}})).status,409);
  const fullTimeId=stranger.body.data.user.id;const fullTimeToken=stranger.body.data.accessToken;
  await db.user.update({where:{id:fullTimeId},data:{employmentType:'FULL_TIME'}});
  await db.scopeGrant.create({data:{userId:hod.body.data.user.id,roleCode:'HOD',departmentId:stranger.body.data.user.departmentId}});
  await db.scopeGrant.create({data:{userId:adminUser.id,roleCode:'PRO_VC',departmentId:stranger.body.data.user.departmentId}});
  const overloadItems=[];
  for(const weeklyHours of ['8','10']){
    const teachingCourse=await db.course.create({data:{code:`TEST-${weeklyHours}`,title:`Synthetic overload ${weeklyHours}`,departmentId:stranger.body.data.user.departmentId}});
    const teachingItem={...item,courseId:teachingCourse.id,weeklyHours};overloadItems.push(teachingItem);
    const assigned=await request('/configuration/lecturer-workloads',{token:adminToken,method:'POST',body:{...assignment,lecturerId:fullTimeId,courseId:teachingCourse.id,weeklyHours}});assert.equal(assigned.status,201);
  }
  const overloadBody={...body,type:'OVERLOAD',items:overloadItems};
  const overload=await request('/claims',{token:fullTimeToken,method:'POST',body:overloadBody,key:randomUUID()});assert.equal(overload.status,201);
  assert.equal((await request(`/claims/${overload.body.data.id}/submit`,{token:fullTimeToken,method:'POST',body:{expectedVersion:1},key:randomUUID()})).status,422);
  const rule=await request('/configuration/workload-rules',{token:adminToken,method:'POST',body:{category:'LECTURER',expectedWeeklyHours:'12',effectiveFrom:'2026-09-01',effectiveTo:'2026-12-31',active:true}});assert.equal(rule.status,201);
  const partial=await request('/claims',{token:fullTimeToken,method:'POST',body:{...overloadBody,items:overloadItems.slice(0,1)},key:randomUUID()});assert.equal(partial.status,201);
  assert.equal((await request(`/claims/${partial.body.data.id}/submit`,{token:fullTimeToken,method:'POST',body:{expectedVersion:1},key:randomUUID()})).status,422);
  const approvedOverload=await request(`/claims/${overload.body.data.id}/submit`,{token:fullTimeToken,method:'POST',body:{expectedVersion:1},key:randomUUID()});assert.equal(approvedOverload.status,201,JSON.stringify(approvedOverload.body));
  const calculated=await request(`/claims/${overload.body.data.id}`,{token:fullTimeToken});assert.equal(calculated.body.data.totalHours,'72');assert.equal(calculated.body.data.eligibleHours,'24');
  console.log('Claim integration passed: ownership, decimal totals, concurrent edits, policy gates, immutable revisions, duplicate coverage, notifications, cancellation.');
}
