import { FormEvent, useEffect, useState } from 'react';
import { Bell, Check, CheckCheck, FilePlus2, RefreshCw, Save, Send, ShieldCheck, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../app/auth';
import { api, patch, post } from '../../services/api';
import { Empty, ErrorNotice, formatDate, Loading, PageHeader, Pagination, Status, useResource } from '../../components/ui';

interface Overview {counts:{status:string;count:number}[];recent:{id:string;reference:string;status:string;totalHours:string;createdAt:string;semester:{name:string};lecturer:{name:string}}[];unread:number;semesters:{name:string;academicYear:{name:string}}[];administration:{users:number;activeUsers:number}|null;}
export function Dashboard(){
  const {user}=useAuth();const result=useResource<{data:Overview}>(()=>api('/workspace'));
  if(result.loading)return <Loading/>;
  if(result.error)return <><ErrorNotice message={result.error}/><button className="button secondary" onClick={result.reload}><RefreshCw size={16}/>Retry</button></>;
  const data=result.data!.data;const count=(statuses:string[])=>data.counts.filter(item=>statuses.includes(item.status)).reduce((sum,item)=>sum+item.count,0);
  const metrics=data.administration?[['Staff accounts',data.administration.users],['Active accounts',data.administration.activeUsers],['Inactive accounts',data.administration.users-data.administration.activeUsers],['Unread notifications',data.unread]]:[['Total claims',data.counts.reduce((sum,item)=>sum+item.count,0)],['In progress',count(['HOD_REVIEW','PRO_VC_REVIEW','AUDIT_REVIEW','AUDIT_CLEARED','FINANCE_PROCESSING','PAYMENT_PENDING'])],['Paid claims',count(['PAID'])],['Returned for correction',count(['RETURNED_FOR_CORRECTION','AUDIT_QUERY'])]];
  return <><section className="workspace-hero"><div><span className="eyebrow">STAFF WORKSPACE</span><h1>Welcome, {user!.name}</h1><p>{data.semesters.length?data.semesters.map(period=>`${period.academicYear.name} / ${period.name}`).join(' | '):'No current academic period'} · {user!.departmentName}</p></div><div className="hero-actions">{user!.permissions.includes('claims.create')&&<Link className="button primary large" to="/claims/new"><FilePlus2 size={17}/>New claim</Link>}<button className="button secondary" title="Refresh overview" aria-label="Refresh overview" onClick={result.reload}><RefreshCw size={17}/>Refresh</button></div></section><section className="metric-grid executive" aria-label="Overview totals">{metrics.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong><small><TrendingUp size={13}/>Live workspace total</small></article>)}</section>
  {data.administration?<section className="workspace-section"><div className="section-heading"><h2>Administration</h2><span>Operate the claim system</span></div><div className="admin-shortcuts"><Link to="/admin/users"><strong>Staff accounts</strong><span>{data.administration.activeUsers} active</span></Link>{user!.permissions.includes('faculties.manage')&&<Link to="/admin/configuration"><strong>Academic records</strong><span>Faculties, departments and teaching periods</span></Link>}</div></section>:<section className="workspace-section"><div className="section-heading"><h2>Recent claims</h2><span>Latest records visible to your role</span></div>{data.recent.length?<div className="claim-card-grid compact">{data.recent.map(claim=><Link className="claim-card" to={`/claims/${claim.id}`} key={claim.id}><div><strong>{claim.reference}</strong><Status status={claim.status}/></div><p>{claim.lecturer.name}</p><dl><dt>Semester</dt><dd>{claim.semester.name}</dd><dt>Hours</dt><dd>{claim.totalHours}</dd></dl></Link>)}</div>:<Empty title="No claims yet" message="There are no claims in your authorized records."/>}</section>}
  <section className="workspace-section"><h2>Notifications</h2><Link className="notification-summary" to="/notifications"><Bell size={20}/><span>{data.unread?`${data.unread} unread notifications`:'You are up to date'}</span><span>View inbox</span></Link></section></>;
}

export function Profile(){
  const {user,reload}=useAuth();const [name,setName]=useState(user!.name);const [title,setTitle]=useState(user!.title);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [current,setCurrent]=useState('');const [password,setPassword]=useState('');const [confirmation,setConfirmation]=useState('');
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{await patch('/profile',{name,title});await reload();setMessage('Profile saved.');}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  async function change(event:FormEvent){event.preventDefault();setError('');setMessage('');if(password!==confirmation){setError('The new passwords do not match.');return;}setBusy(true);try{await post('/profile/change-password',{currentPassword:current,password});setCurrent('');setPassword('');setConfirmation('');setMessage('Password changed. Other sessions have been signed out.');}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <><PageHeader title="My profile"/><ErrorNotice message={error}/>{message&&<p className="success-notice" role="status"><Check size={17}/>{message}</p>}<section className="workspace-section profile-grid"><div><h2>Personal details</h2><dl className="record-details"><dt>Staff ID</dt><dd>{user!.staffId}</dd><dt>Email</dt><dd>{user!.email}</dd><dt>Department</dt><dd>{user!.departmentName}</dd><dt>Employment</dt><dd>{user!.employmentType.replace('_',' ')}</dd></dl></div><form onSubmit={save}><label>Full name<input required minLength={3} maxLength={100} value={name} onChange={event=>setName(event.target.value)}/></label><label>Title<input maxLength={80} value={title} onChange={event=>setTitle(event.target.value)}/></label><button className="button primary" disabled={busy}><Save size={16}/>Save profile</button></form></section><section className="workspace-section profile-grid"><div><h2>Password</h2><ShieldCheck className="profile-shield" size={32}/></div><form onSubmit={change}><label>Current password<input required type="password" autoComplete="current-password" value={current} onChange={event=>setCurrent(event.target.value)}/></label><label>New password<input required type="password" minLength={12} maxLength={72} autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)}/></label><label>Confirm new password<input required type="password" minLength={12} maxLength={72} autoComplete="new-password" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button className="button primary" disabled={busy}><ShieldCheck size={16}/>Change password</button></form></section></>;
}

interface Notification {id:string;title:string;message:string;readAt:string|null;createdAt:string;claimId:string|null;}
export function Notifications(){
  const {user}=useAuth();const canBroadcast=user!.permissions.includes('notifications.broadcast');
  const [page,setPage]=useState(1);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [broadcast,setBroadcast]=useState({audience:'ALL',title:'',message:''});const result=useResource<{data:Notification[];meta:{total:number}}>(()=>api(`/notifications?page=${page}&pageSize=10`),[page]);
  useEffect(()=>{if(result.data?.data.some(item=>!item.readAt))post('/notifications/read-all').then(()=>{window.dispatchEvent(new Event('notifications-read'));result.reload();}).catch(()=>{});},[result.data?.data]);
  async function mark(id?:string){setBusy(true);setError('');try{if(id)await patch(`/notifications/${id}/read`,{});else await post('/notifications/read-all');window.dispatchEvent(new Event('notifications-read'));result.reload();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  async function send(event:FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{const result=await post('/notifications/broadcast',broadcast) as {data:{recipients:number}};setBroadcast({audience:'ALL',title:'',message:''});setMessage(`Notification sent to ${result.data.recipients} user${result.data.recipients===1?'':'s'}.`);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <><PageHeader title="Notifications" action={<button className="button secondary" disabled={busy||!result.data?.meta.total} onClick={()=>mark()}><CheckCheck size={17}/>Mark all read</button>}/><ErrorNotice message={error||result.error}/>{message&&<p className="success-notice" role="status"><Check size={17}/>{message}</p>}{canBroadcast&&<section className="workspace-section notification-composer"><h2>Send announcement</h2><form onSubmit={send}><div className="form-grid"><label>Audience<select value={broadcast.audience} onChange={event=>setBroadcast(current=>({...current,audience:event.target.value}))}><option value="ALL">All users</option><option value="LECTURER">Lecturers</option><option value="HOD">Heads of Department</option><option value="PRO_VC">Pro VC</option><option value="FINANCE">Finance</option><option value="AUDITOR">Auditors</option><option value="ADMIN">Administrators</option></select></label><label>Title<input required minLength={4} maxLength={120} value={broadcast.title} onChange={event=>setBroadcast(current=>({...current,title:event.target.value}))}/></label><label className="full-width">Message<textarea required minLength={8} maxLength={1000} value={broadcast.message} onChange={event=>setBroadcast(current=>({...current,message:event.target.value}))}/></label></div><button className="button primary" disabled={busy}><Send size={16}/>{busy?'Sending...':'Send notification'}</button></form></section>}{result.error&&<button className="button secondary" onClick={result.reload}>Retry</button>}{result.loading?<Loading/>:result.data?.data.length?<><ul className="notification-list">{result.data.data.map(item=><li key={item.id} className={item.readAt?'':'unread'}><Bell size={18}/><div><h2>{item.claimId?<Link className="record-link" to={`/claims/${item.claimId}`}>{item.title}</Link>:item.title}</h2><p>{item.message}</p><time>{formatDate(item.createdAt)}</time></div>{!item.readAt&&<button className="icon-button" disabled={busy} title="Mark read" aria-label={`Mark ${item.title} read`} onClick={()=>mark(item.id)}><Check size={18}/></button>}</li>)}</ul><Pagination page={page} total={result.data.meta.total} pageSize={10} onPage={setPage}/></>:!result.error&&<Empty title="All caught up" message="You have no notifications."/>}</>;
}
