ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'AUDIT_REVIEW';
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'AUDIT_CLEARED';
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'AUDIT_QUERY';
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'AUDIT_REJECTED';
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'AWAITING_PAYMENT';
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_FAILED';
