import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, ShieldCheck, FileCheck2, Workflow, CreditCard, GraduationCap, ChevronRight, MapPin } from 'lucide-react';
import { useAuth, homeFor } from '../../app/auth';
export function Landing(){const {user}=useAuth();return <div className="landing">
  <div className="university-strip"><span>University of Professional Studies, Accra</span><a href="https://upsa.edu.gh/" target="_blank" rel="noreferrer">Visit university website <ArrowUpRight size={13}/></a></div>
  <header className="public-header"><Link to="/" aria-label="UPSA home"><img src="/images/upsa-logo.png" alt="University of Professional Studies, Accra"/></Link><nav><a href="#how-it-works">How it works</a><a href="#resources">Staff resources</a><Link className="button primary" to={user?homeFor(user):'/login'}>{user?'Open workspace':'Staff sign in'}<ArrowUpRight size={16}/></Link></nav></header>
  <main><section className="landing-hero"><div className="landing-copy"><div className="portal-label"><span/> THE LECTURER CLAIMS PORTAL</div><h1>More time for<br/>what you do <em>best.</em></h1><p>A simpler way to manage your teaching claims.<br className="desktop-break"/> Submit, follow approvals, and track payments —<br className="desktop-break"/> all from one connected workspace.</p><Link to={user?homeFor(user):'/login'} className="button gold large">Enter your workspace <ArrowRight size={18}/></Link><div className="secure-note"><ShieldCheck size={17}/><span>Secure access for UPSA academic and administrative staff</span></div></div><div className="campus-visual"><img src="/images/campus.jpg" alt="University of Professional Studies, Accra campus"/><div className="campus-gradient"/><div className="campus-caption"><span className="caption-line"/><div><span>KNOWLEDGE. EXCELLENCE. SERVICE.</span><h2>A university built<br/>on professionalism.</h2><p><MapPin size={14}/> Accra, Ghana</p></div></div><div className="image-label"><GraduationCap size={18}/> Built for our academic community</div></div></section>
  <section className="value-strip"><div><ShieldCheck/><span>Secure by design<small>Access tailored to your role</small></span></div><div><Workflow/><span>Clear at every step<small>From submission to final approval</small></span></div><div><FileCheck2/><span>A complete record<small>Your claims and history, together</small></span></div></section>
  <section id="how-it-works" className="how-section"><div className="section-intro"><span className="eyebrow">LESS PAPERWORK. MORE CLARITY.</span><h2>Your claim, from start to finish.</h2><p>One straightforward process. Visibility at every stage.</p></div><div className="process-grid">{[{icon:FileCheck2,title:'Submit your claim',text:'Add your courses and teaching hours, review the details, and submit for verification.'},{icon:Workflow,title:'Follow the review',text:'Stay informed as your department and the Pro VC review your teaching claim.'},{icon:CreditCard,title:'Track your payment',text:'See when Finance processes your approved claim and records payment.'}].map((item,i)=><article key={item.title}><span className="process-number">0{i+1}</span><div className="process-icon"><item.icon size={25}/></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
  <section id="resources" className="resources-section"><div><span className="eyebrow">STAY CONNECTED</span><h2>Part of your university workspace.</h2><p>Find academic information and resources on the official UPSA website.</p></div><div className="resource-links"><a href="https://upsa.edu.gh/academics/" target="_blank" rel="noreferrer">Academic information<ArrowUpRight size={20}/></a><a href="https://upsa.edu.gh/" target="_blank" rel="noreferrer">University news and announcements<ArrowUpRight size={20}/></a><Link to="/login">Access your staff portal<ChevronRight size={20}/></Link></div></section></main>
  <footer className="public-footer"><span>© {new Date().getFullYear()} UPSA · Lecturer Claims Portal</span><span>University of Professional Studies, Accra <span className="footer-dot">·</span> Ghana</span></footer>
  </div>;}
