import { useState, FormEvent } from 'react';
import { Link, Navigate, useSearchParams } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, LockKeyhole, ShieldCheck } from 'lucide-react';
import { useAuth, homeFor } from '../../app/auth';
import { ErrorNotice } from '../../components/ui';
import { post } from '../../services/api';
export function Login(){
  const {user,login}=useAuth();const [identifier,setIdentifier]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [help,setHelp]=useState(false);
  if(user)return <Navigate to={homeFor(user)} replace/>;
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await login(identifier,password);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="login-page"><div className="login-story"><img className="login-campus" src="/images/campus.jpg" alt="UPSA campus"/><div className="login-overlay"/><div className="login-story-copy"><div className="portal-label light">UPSA LECTURER CLAIMS PORTAL</div><h1>Supporting the people<br/>who shape the future.</h1><p>Your teaching matters. We make the paperwork simpler.</p><div className="login-story-line"/></div><span className="login-location">University of Professional Studies, Accra · Ghana</span></div><main className="login-form-side"><img className="login-logo" src="/images/upsa-logo.png" alt="UPSA"/><div className="login-form-wrap"><span className="eyebrow">YOUR STAFF WORKSPACE</span><h1>Welcome back.</h1><p>Sign in to manage your claims and approvals.</p><form onSubmit={submit}><ErrorNotice message={error}/><label>Staff ID or email address<input autoComplete="username" required value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Enter your staff ID or email"/></label><label>Password<div className="password-input"><input autoComplete="current-password" type={show?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button type="button" className="text-button forgot" onClick={()=>setHelp(!help)}>Need help signing in?</button>{help&&<div className="info-box">Contact your university portal administrator to activate your account or request a secure password-reset link.</div>}<button className="button primary full large" disabled={busy}>{busy?'Signing in…':'Sign in to your workspace'}<ArrowRight size={18}/></button></form><div className="login-security"><ShieldCheck size={20}/><p>Protected access<small>Your account permissions determine the records you can view and manage.</small></p></div></div><div className="login-bottom"><LockKeyhole size={13}/> Authorized university staff only</div></main></div>;
}
export function ResetPassword(){const [params]=useSearchParams();const [password,setPassword]=useState('');const [error,setError]=useState('');const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);return <div className="standalone"><div className="panel reset-panel"><img src="/images/upsa-logo.png" alt="UPSA"/><h1>Reset your password</h1>{done?<><p>Your password has been updated.</p><Link className="button primary" to="/login">Sign in</Link></>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('/auth/reset-password',{token:params.get('token'),password});setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><ErrorNotice message={error}/><label>New password<input type="password" minLength={12} maxLength={128} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/><small>Use at least 12 characters.</small></label><button disabled={busy} className="button primary">{busy?'Updating…':'Update password'}</button></form>}</div></div>;}
